### ISSUE TITLE
Compile errors for missing CapacitiveSensor.h

### ISSUE THREAD

**Issue by kellySmi** [arduino-libraries/EducationShield#10]
When including the education shield library in the Arduino IDE, there is an error that says the CapacitiveSensor.h is not found. I have resolved this by copying both the CapacitiveSensor.h and CapacitiveSensor.cpp files into the src directory and restarted the IDE.

**Comment by kellySmi** [comment]
I tried adding the CapacitiveSensor using the Library Manager, also removing the previous workaround, and I got many errors informing me of "Multiple libraries were found for 'Servo.h'"

**Comment by per1234** [comment]
>I got many errors informing me of "Multiple libraries were found for 'Servo.h'"

There is no such error. That is just some helpful information the Arduino IDE provides you and it has absolutely nothing to do with installing the CapacitiveSensor library via Library Manager. As long as the expected Servo library is being used you can just ignore it.

Unless you have a verified bug to report, you're better to post in the Arduino Forum:
http://forum.arduino.cc/
I'm sure we can help you with any problems or questions over there.

**Comment by per1234** [comment]
Fixed by https://github.com/arduino-libraries/EducationShield/commit/026571872e953c10247ed44a2c6a7776a521644f
