### ISSUE TITLE
Link in comment is a 404

### ISSUE THREAD

**Issue by charlesbones** [arduino-libraries/EducationShield#21]
The link in the top comment of this code return a 404
https://github.com/arduino-libraries/EducationShield/blob/9d428278e6e81c8e75386672248c1cfa308dd05c/examples/Help/Player/Player.ino#L5

**Comment by per1234** [comment]
If there are no plans to fix the website, the link could be changed to the Wayback Machine's archive of this content:
http://web.archive.org/web/20150731231913/http://cuartielles.com/verkstad/en/Reference/PrepareWavSound

**Comment by charlesbones** [comment]
@per1234 we will change it
